var	mobileMenu         = require('./mobile-menu'),
	masthead           = require('./masthead'),
	responsiveVideo    = require('./responsive-video'),
	setMatchHeight     = require('./set-match-height'),
	loadForms          = require('./load-forms'),
	setValidation      = require('./set-validation'),
	setPlaceholders    = require('./set-placeholders'),
	chosenSelect       = require('./chosen-select'),
	waves              = require('./vendor/waves');
